### ISSUE TITLE
godep: error downloading dep (github.com/dwarvesf/glod): exit status 128

### ISSUE THREAD

**Issue by Bencyril** [dwarvesf/glod-cli#1]
Seems we can restore the depencies :

```
$ godep restore
# cd $GOPATH/src/github.com/dwarvesf/glod; git checkout 391741190a8452537a65b3fca8b38370e5b33e9b
fatal: reference is not a tree: 391741190a8452537a65b3fca8b38370e5b33e9b
godep: error downloading dep (github.com/dwarvesf/glod): exit status 128
godep: Error downloading some deps. Aborting restore and check. 
```

**Comment by RuniVN** [comment]
Hi Bencyril,
Give it a try
```
go get -u github.com/dwarvesf/glod
godep update github.com/dwarvesf/glod
godep restore
```

**Comment by Bencyril** [comment]
```
$ godep update github.com/dwarvesf/glod
godep: not in manifest: github.com/dwarvesf/glod
godep: Package (github.com/stretchr/testify/assert) not found
```

**Comment by Bencyril** [comment]
Seems I forgot something when I wanted to install.
go install github.com/dwarvesf/glod-cli

Instead I git cloned the repo, try to godep the depencies, but didn't works.

But now, it works exept when they're no arguments :
`$ glod-cli
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x42ae40, 0xc82000a0b0)
	/Users/ben/.gvm/gos/go1.6/src/runtime/panic.go:464 +0x3e6
main.main.func1(0xc820088780)
	/Users/ben/go/src/github.com/dwarvesf/glod-cli/main.go:42 +0xa8
github.com/codegangsta/cli.(*App).Run(0xc820088640, 0xc82000a260, 0x1, 0x1, 0x0, 0x0)
	/Users/ben/go/src/github.com/codegangsta/cli/app.go:192 +0x117d
main.main()
	/Users/ben/go/src/github.com/dwarvesf/glod-cli/main.go:45 +0x28a`

**Comment by RuniVN** [comment]
Yes, I have fixed this bug a few hours ago. It shows usage instead panic. Maybe next submission. 
Thank you.
