### ISSUE TITLE
Maybe join forces with ytdl?

### ISSUE THREAD

**Issue by akavel** [dwarvesf/glod-cli#4]
See: https://github.com/otium/ytdl - I've seen it show up some time ago. If not join forces, it would be helpful to at least provide info what are differences between your project and the other one.

**Comment by tieubao** [comment]
@akavel this cli is liked the example for the core library https://github.com/dwarvesf/glod. If you are building your music streaming website, the command line tool to download media files or even a crawler ... you do not have to build it from scratch, glod is here to help. 

And it may be the main difference that I can point out at the moment.
