### ISSUE TITLE
Doesn't compile on Windows due to use of pb.StartPool

### ISSUE THREAD

**Issue by conoro** [dwarvesf/glod-cli#5]
Hi,

I can't get this to install on Windows unless I comment out 

pool, err := pb.StartPool(barList...)
and
pool.Stop()

in commands.go

Multiple progress bars aren't supported on Windows. Any way to work around other than that?

Thanks

**Comment by RuniVN** [comment]
Hi conoro,

Because multi progress bars are not supported on Windows, so comment out these line of code might be the first choice to fix it.
I'm gonna try to replace this progress bar by another library.

**Comment by RuniVN** [comment]
Maybe I will disable multi progress bars in Windows.

**Comment by conoro** [comment]
@RuniVn thanks !
